all:
  vars:
    env: production
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
      ansible_host: 192.168.1.171
    client2:
      ansible_host: 192.168.1.172
    client3:
      ansible_host: 192.168.1.173
    client4:
      ansible_host: 192.168.1.174

master:
  hosts:
    master-node:
      ansible_host: 192.168.1.170